### ISSUE TITLE
Changing font 

### ISSUE THREAD

**Issue by svannib** [matteodelucchi/ZHAW_thesis-template#7]
Dear all,

maybe this is trivial, but i'm having trouble changing the font of the whole document to helvetica. Is this doable?

i tried changing `preamble.tex`, line 11-13

```
% Set main fonts
% Fonts catalogue: https://tug.org/FontCatalogue/
\usepackage{helvet}        % Use the helvetica font by default  
```

**Comment by matteodelucchi** [comment]
Hi svannib,

Sorry for the late response. 
I added a "switch" in [main.tex](https://github.com/matteodelucchi/ZHAW_thesis-template/blob/7379ec71d9f050cc95a7f3fb6598ea77f5b5fc8b/main.tex). If you uncomment [this line](https://github.com/matteodelucchi/ZHAW_thesis-template/blob/7379ec71d9f050cc95a7f3fb6598ea77f5b5fc8b/main.tex#L34) the pdf will be generated with the helvetica font face.
Let me know if this is what you were looking for and if everything runs smoothly so that I can then merge this to the master branch.

**Comment by matteodelucchi** [comment]
Merged in master branch and closing this now.
